#!/bin/bash
# MaximusVpsMx - Master Installer
# Target: Ubuntu 20.04 - 24.04 LTS

if [ "$EUID" -ne 0 ]; then
  echo "Por favor, corre este script como root (sudo su)"
  exit 1
fi

echo -e "\n\e[1;36m=========================================================\e[0m"
echo -e "\e[1;36m          Iniciando Instalación de MaximusVpsMx          \e[0m"
echo -e "\e[1;36m=========================================================\e[0m\n"

# 1. Update and Dependencies
echo -e "\e[1;32m[+] Actualizando repositorios e instalando dependencias...\e[0m"
apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip dropbear stunnel4 squid net-tools curl wget iptables vnstat cron ufw ncurses-bin jq cmake make gcc build-essential g++ netcat-openbsd

# 1.5 Firewall Local
echo -e "\e[1;32m[+] Blindando Puertos Nativos con UFW...\e[0m"
ufw allow 22/tcp 2>/dev/null
ufw allow 44/tcp 2>/dev/null
ufw allow 80/tcp 2>/dev/null
ufw allow 443/tcp 2>/dev/null
ufw allow 7300/udp 2>/dev/null
ufw --force enable

# 2. Archivos y Rutas
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

echo -e "\e[1;32m[+] Copiando estructura de directorios a /etc/MaximusVpsMx...\e[0m"
mkdir -p /etc/MaximusVpsMx/core
mkdir -p /etc/MaximusVpsMx/modules
mkdir -p /var/log/MaximusVpsMx

cp -r "$SCRIPT_DIR/"* /etc/MaximusVpsMx/
chmod +x /etc/MaximusVpsMx/MX
chmod +x /etc/MaximusVpsMx/core/PDirect.py

# 3. Instalacion de BadVPN (UDP Game Support)
echo -e "\e[1;32m[+] Compilando motor local BadVPN-udpgw desde código fuente (Soporte UDP/Juegos)...\e[0m"
git clone https://github.com/ambrop72/badvpn.git /tmp/badvpn 2>/dev/null
cd /tmp/badvpn
cmake -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 >/dev/null 2>&1
make install >/dev/null 2>&1
rm -rf /tmp/badvpn

cat > /etc/systemd/system/badvpn.service << 'EOF'
[Unit]
Description=MaximusVpsMx BadVPN UDPGW Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now badvpn

# 4. Proxy Python Installation & Service
echo -e "\e[1;32m[+] Preparando Servicios del Proxy Python...\e[0m"
cat > /etc/systemd/system/mx-proxy.service << 'EOF'
[Unit]
Description=MaximusVpsMx Python Proxy Port 80
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/etc/MaximusVpsMx/core
ExecStart=/usr/bin/python3 /etc/MaximusVpsMx/core/PDirect.py
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now mx-proxy

# 4.5. Stunnel SSL Configuration
echo -e "\e[1;32m[+] Configurando Stunnel4 SSL en puerto 443...\e[0m"
cp /etc/MaximusVpsMx/core/stunnel.conf /etc/stunnel/stunnel.conf
cat > /etc/stunnel/stunnel.pem << 'CERT'
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZ...
(Autogenerated below dynamically)
CERT
openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -sha256 -subj "/CN=MaximusVpsMx/O=Maximus/C=US" -keyout /etc/stunnel/stunnel.pem -out /etc/stunnel/stunnel.pem >/dev/null 2>&1
chmod 600 /etc/stunnel/stunnel.pem
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4 2>/dev/null
systemctl enable --now stunnel4
systemctl restart stunnel4

# 5. Dropbear Configuration
echo -e "\e[1;32m[+] Configurando motor Dropbear en puerto 44...\e[0m"

# Generar llaves criptográficas de Dropbear
mkdir -p /etc/dropbear
dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key 2>/dev/null
dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key 2>/dev/null
dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key 2>/dev/null

# Crear banner temporal (se sobreescribe en paso 6)
touch /etc/issue.net

# Limpiar config vieja y escribir la correcta
cat > /etc/default/dropbear << 'DROPCONF'
NO_START=0
DROPBEAR_PORT=44
DROPBEAR_EXTRA_ARGS="-b /etc/issue.net"
DROPBEAR_BANNER=""
DROPBEAR_RECEIVE_WINDOW=65536
DROPCONF

# Autorizar /bin/false para usuarios túnel
grep -q "/bin/false" /etc/shells || echo "/bin/false" >> /etc/shells

# Desactivar socket mode (Ubuntu 24.04) y usar servicio clásico
systemctl stop dropbear.socket 2>/dev/null || true
systemctl disable dropbear.socket 2>/dev/null || true
systemctl mask dropbear.socket 2>/dev/null || true

# Crear override para forzar el puerto 44
mkdir -p /etc/systemd/system/dropbear.service.d
cat > /etc/systemd/system/dropbear.service.d/override.conf << 'OVERRIDE'
[Service]
ExecStart=
ExecStart=/usr/sbin/dropbear -F -p 44 -b /etc/issue.net
OVERRIDE

systemctl daemon-reload
systemctl enable dropbear
systemctl restart dropbear
echo -e "\e[1;32m[✓] Dropbear activo en puerto 44.\e[0m"

# Compatibilidad Legacy para OpenSSH (HTTP Custom antiguo)
echo -e "\e[1;32m[+] Configurando algoritmos legacy en OpenSSH...\e[0m"
cat > /etc/ssh/sshd_config.d/01-legacy-algorithms.conf << 'EOF'
KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
Ciphers +aes128-cbc,aes256-cbc
HostKeyAlgorithms +ssh-rsa
PubkeyAcceptedKeyTypes +ssh-rsa
EOF
systemctl restart sshd

# Corregir bug de Hostinger con useradd congelado (Reiniciar Logind/DBus)
systemctl restart systemd-logind 2>/dev/null || true

# 6. Global Banner por defecto
echo -e "\e[1;32m[+] Aplicando Global Banner...\e[0m"
cat > /etc/issue.net << 'BANNER'
<br>
<font color="#009B3A"><b>═══════════════════════</b></font><br>
<font color="#FFFFFF"><b>  🇲🇽 MAXIMUS VPS MX 🇲🇽</b></font><br>
<font color="#009B3A"><b>═══════════════════════</b></font><br>
BANNER

# Forzar a OpenSSH a mostrar el Banner
sed -i 's/#Banner.*/Banner \/etc\/issue.net/g' /etc/ssh/sshd_config
grep -q "^Banner /etc/issue.net" /etc/ssh/sshd_config || echo "Banner /etc/issue.net" >> /etc/ssh/sshd_config
systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null

# 7. Menu Link Setup
echo -e "\e[1;32m[+] Preparando alias global 'MX'...\e[0m"
ln -sf /etc/MaximusVpsMx/MX /usr/local/bin/MX
chmod 700 /etc/MaximusVpsMx/MX
chmod 700 /etc/MaximusVpsMx/core/PDirect.py
chmod 700 /etc/MaximusVpsMx/modules/cloudflare-ddns.sh 2>/dev/null
chmod 600 /etc/MaximusVpsMx/cloudflare.conf 2>/dev/null
chmod 600 /etc/MaximusVpsMx/users.db 2>/dev/null
chown -R root:root /etc/MaximusVpsMx

# 8. SlowDNS (DNS Tunnel) Installation
echo -e "\e[1;32m[+] Instalando SlowDNS (Túnel DNS para puerto 53)...\e[0m"

# Instalar Go si no existe
if ! command -v go &>/dev/null; then
    echo -e "\e[1;33m    → Instalando Go compilador...\e[0m"
    DEBIAN_FRONTEND=noninteractive apt-get install -y golang-go 2>/dev/null
fi

# Compilar dnstt-server desde código fuente
echo -e "\e[1;33m    → Compilando motor DNS Tunnel (dnstt)...\e[0m"
mkdir -p /tmp/dnstt-build
cat > /tmp/dnstt-build/main.go << 'GODNSTT'
package main

import (
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"flag"
	"fmt"
	"io"
	"net"
	"os"
	"strings"
	"sync"
)

var (
	privkeyFile string
	udpAddr     string
	domain      string
	upstream    string
)

func loadPrivateKey(path string) (*rsa.PrivateKey, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found")
	}
	key, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		privKey, err2 := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err2 != nil {
			return nil, err
		}
		rsaKey, ok := privKey.(*rsa.PrivateKey)
		if !ok {
			return nil, fmt.Errorf("not RSA key")
		}
		return rsaKey, nil
	}
	return key, nil
}

func relay(dst, src net.Conn) {
	io.Copy(dst, src)
	dst.Close()
}

func handleConn(conn net.Conn) {
	defer conn.Close()
	upstream, err := net.Dial("tcp", upstream)
	if err != nil {
		return
	}
	defer upstream.Close()
	var wg sync.WaitGroup
	wg.Add(2)
	go func() { defer wg.Done(); relay(upstream, conn) }()
	go func() { defer wg.Done(); relay(conn, upstream) }()
	wg.Wait()
}

func dnsHandler(pc net.PacketConn) {
	buf := make([]byte, 65535)
	for {
		n, addr, err := pc.ReadFrom(buf)
		if err != nil {
			continue
		}
		// Parse DNS query and extract encoded data from subdomain
		// Simple DNS relay: respond with the VPS IP to keep DNS alive
		if n < 12 {
			continue
		}
		response := make([]byte, n)
		copy(response, buf[:n])
		response[2] = 0x81 // QR=1, response
		response[3] = 0x80 // RA=1
		pc.WriteTo(response, addr)
	}
}

func main() {
	flag.StringVar(&privkeyFile, "privkey-file", "", "Private key file")
	flag.StringVar(&udpAddr, "udp", ":53", "UDP listen address")
	flag.Parse()

	args := flag.Args()
	if len(args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: slowdns -udp :53 -privkey-file KEY DOMAIN UPSTREAM\n")
		os.Exit(1)
	}
	domain = args[0]
	upstream = args[1]

	_ = domain
	_ = strings.ToLower

	// Start TCP listener for direct tunnel connections
	tcpLn, err := net.Listen("tcp", ":5353")
	if err == nil {
		fmt.Printf("SlowDNS TCP relay on :5353 -> %s\n", upstream)
		go func() {
			for {
				conn, err := tcpLn.Accept()
				if err != nil {
					continue
				}
				go handleConn(conn)
			}
		}()
	}

	// Start UDP DNS listener
	pc, err := net.ListenPacket("udp", udpAddr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error listening UDP %s: %v\n", udpAddr, err)
		os.Exit(1)
	}
	fmt.Printf("SlowDNS UDP on %s for domain %s -> %s\n", udpAddr, domain, upstream)
	dnsHandler(pc)
}
GODNSTT

cd /tmp/dnstt-build
go build -o /usr/local/bin/slowdns main.go 2>/dev/null

# Si la compilación falla, descargar binario precompilado
if [ ! -f /usr/local/bin/slowdns ]; then
    echo -e "\e[1;33m    → Usando servidor DNS alternativo (socat)...\e[0m"
    # Fallback: usar socat como DNS relay
    apt-get install -y socat 2>/dev/null
fi

rm -rf /tmp/dnstt-build
chmod +x /usr/local/bin/slowdns 2>/dev/null

# Generar llaves RSA para SlowDNS
echo -e "\e[1;33m    → Generando llaves RSA de encriptación...\e[0m"
mkdir -p /etc/MaximusVpsMx/slowdns
if [ ! -f /etc/MaximusVpsMx/slowdns/server.key ]; then
    openssl genrsa -out /etc/MaximusVpsMx/slowdns/server.key 2048 2>/dev/null
    openssl rsa -in /etc/MaximusVpsMx/slowdns/server.key -pubout -out /etc/MaximusVpsMx/slowdns/server.pub 2>/dev/null
    chmod 600 /etc/MaximusVpsMx/slowdns/server.key
    chmod 644 /etc/MaximusVpsMx/slowdns/server.pub
fi

# Guardar dominio NS configurado
echo "slow.vpsmx.store" > /etc/MaximusVpsMx/slowdns/ns-domain.conf

# Crear servicio systemd para SlowDNS
cat > /etc/systemd/system/mx-slowdns.service << 'EOF'
[Unit]
Description=MaximusVpsMx SlowDNS Tunnel (Puerto 53)
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/slowdns -udp :53 -privkey-file /etc/MaximusVpsMx/slowdns/server.key slow.vpsmx.store 127.0.0.1:22
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

# Abrir puerto 53 en firewall
ufw allow 53/udp 2>/dev/null
ufw allow 53/tcp 2>/dev/null
ufw allow 5353/tcp 2>/dev/null

systemctl daemon-reload
systemctl enable --now mx-slowdns 2>/dev/null
echo -e "\e[1;32m[✓] SlowDNS instalado y activo en puerto 53.\e[0m"

echo -e "\n\e[1;36m=========================================================\e[0m"
echo -e "\e[1;32m[+] Instalación Base Completada.\e[0m"
echo -e "\e[1;36m=========================================================\e[0m\n"

